// ESP8266WiFi.h - esp8266 Wifi support.
// Based on WiFi.h from Arduino WiFi shield library.
// Copyright (c) 2011-2014 Arduino.  All right reserved.
// Modified by Ivan Grokhotkov, December 2014

// Pubsubclient library - 2008-2020 Nicholas O'Leary - https://github.com/knolleary/pubsubclient

/* time.h -- An implementation of the standard Unix <sys/time.h> file.
   Written by Geoffrey Noer <noer@cygnus.com>
   Public domain; no rights reserved. */

// TZ.h - autogenerated from https://raw.githubusercontent.com/nayarsystems/posix_tz_db/master/zones.csv
// by script <esp8266 arduino core>/tools/TZupdate.sh
// Mon Mar 20 22:00:17 UTC 2023
//
// This database is autogenerated from IANA timezone database
//    https://raw.githubusercontent.com/nayarsystems/posix_tz_db/master/zones.csv
//    (using https://www.iana.org/time-zones)
// and can be updated on demand in this repository
// or by yourself using the above script

// LittelFS library - Copyright (c) 2023 Earle F. Philhower, III earlephilhower@yahoo.com
// Permission is hereby granted, free of charge, 
// to any person obtaining a copy of this software and associated documentation files (the "Software"), 
// to deal in the Software without restriction, 
// including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or 
// sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

/*
  CertStoreBearSSL.h - Library for Arduino ESP8266
  Copyright (c) 2018 Earle F. Philhower, III

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

// String library - Components for manipulating sequences of characters -*- C++ -*-
// Copyright (C) 1997-2020 Free Software Foundation, Inc.

// TinyGPSPlus library - mikal hart - https://github.com/mikalhart/TinyGPSPlus

// SoftwareSerial.h - Implementation of the Arduino software serial for ESP8266/ESP32.
// Copyright (c) 2015-2016 Peter Lerup. All rights reserved.
// Copyright (c) 2018-2019 Dirk O. Kaar. All rights reserved.


#include <ESP8266WiFi.h>
#include <PubSubClient.h>
#include <time.h>
#include <TZ.h>
#include <LittleFS.h>
#include <CertStoreBearSSL.h>
#include <string>
#include <TinyGPSPlus.h>
#include <SoftwareSerial.h>

// Định nghĩa các chân kết nối của cảm biến
#define waterLevel_Sensor A0
#define openDoor_Sensor 15
static const int RXPin = 4, TXPin = 14;
static const uint32_t GPSBaud = 9600;

// Khởi tạo GPS
TinyGPSPlus gps;
SoftwareSerial ss(RXPin, TXPin);

// Setup wifi và server mqtt
const char* ssid = "wifi";
const char* password = "88888888";
const char* mqtt_server = "dbdd316e91e448408b3570eb798874b2.s1.eu.hivemq.cloud";

// Khởi tạo thư viện phục vụ kết nối SSL tới server mqtt
BearSSL::CertStore certStore;

// Định nghĩa wifi và đối tượng pubsubclient để giao tiếp tới server
WiFiClientSecure espClient;
PubSubClient * client;
unsigned long lastMsg = 0;

// Kết nối wifi
void setup_wifi() {
  delay(10);

  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);

  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  randomSeed(micros());

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
}

// Thiết lập ngày giờ cho mạch
void setDateTime() {
  configTime(TZ_Etc_GMT0, "pool.ntp.org", "time.nist.gov");

  Serial.print("Waiting for NTP time sync: ");
  time_t now = time(nullptr);
  while (now < 8 * 3600 * 2) {
    delay(100);
    Serial.print(".");
    now = time(nullptr);
  }
  Serial.println();

  struct tm timeinfo;
  gmtime_r(&now, &timeinfo);
  
  Serial.printf("%s %s", tzname[0], ctime(&now));
  Serial.println(now);
}

// Cách lấy thời gian gửi đi 1: Lấy ngày giờ từ server NTP
String getDateTimeNTP(){
  time_t timestamp = time(nullptr)+ 7 * 3600;
  for (int i = 0; i <= 10; i++){ 
    if (timestamp >= 8 * 3600 * 2) {
      delay(100);
      Serial.println(".");
      timestamp = time(nullptr) + 7 * 3600;
      break;
    } else if (i == 10){
      return "-1";
    }
  }
  Serial.println(timestamp);

  int monthInNormalYear[12] = { 31,28,31,30,31,30,31,31,30,31,30,31 };
  int monthInLeapYear[12] = { 31,29,31,30,31,30,31,31,30,31,30,31 };

  const int secondsTo2025 = 1735603200;
  int secondsPerDay = 3600 * 24;
  int secondsPerLeapYear = 366 * secondsPerDay;
  int secondsPerNormalYear = 365 * secondsPerDay;

  int remainSeconds = timestamp - secondsTo2025;

  int year = 2025;
  int month = 0;
  int day = 0;
  int hour = 0;
  int min = 0;
  int second = 0;

  while (true) {
      if (year % 4 == 0 || year % 400 == 0) {
          if (remainSeconds > secondsPerLeapYear) {
              remainSeconds -= secondsPerLeapYear;
          }
          else {
              break;
          }
      }
      else {
          if (remainSeconds > secondsPerNormalYear) {
              remainSeconds -= secondsPerNormalYear;
          }
          else {
              break;
          }
      }
      year += 1;
  }

  int numDay = remainSeconds / secondsPerDay;
  remainSeconds -= numDay * secondsPerDay;

  if (year % 4 == 0 || year % 400 == 0) {
      for (int i = 1; i <= 12; i++) {
          if (numDay > monthInLeapYear[i-1]) {
              numDay -= monthInLeapYear[i-1];
          }
          else {
              month = i;
              day = numDay;
              break;
          }
      }
  }
  else {
      for (int i = 1; i <= 12; i++) {
          if (numDay > monthInNormalYear[i - 1]) {
              numDay -= monthInNormalYear[i - 1];
          }
          else {
              month = i;
              day = numDay;
              break;
          }
      }
  }

  hour = remainSeconds / 3600;
  remainSeconds -= hour * 3600;
  min = remainSeconds / 60;
  remainSeconds -= min * 60;
  second = remainSeconds;


  String time = String(hour) + ":" + String(min) + ":" + String(second);
  String date = String(day) + "/" + String(month) + "/" + String(year);
  Serial.println(time);
  Serial.println(date);
  return date + "," + time;
}

// Cách lấy thời gian gửi đi 2: Chuyển ngày giờ nhận từ GPS sang múi giờ việt nam để gửi đi
String parseToGMT7(int y, int m, int d, int h, int min, int second){
  int monthInNormalYear [12] = {31,28,31,30,31,30,31,31,30,31,30,31};
  int monthInLeapYear [12] = {31,29,31,30,31,30,31,31,30,31,30,31};

  int year = y;
  int month = m;
  int day = d;
  int hour = h + 7;;

  // Tăng thêm 7 giờ
  if (hour >= 24){
    hour -= 24;

    day += 1;
    // Xét năm nhuận
    if (year % 4 == 0 || year % 400 == 0){
      if (day > monthInLeapYear[month - 1]){
        day = 1;
        if (month == 12){
          year += 1;
          month = 1;
        } else {
          month += 1;
        }
      }
    } else {
      // Xét năm không nhuận
      if (day > monthInNormalYear[month - 1]){
        day = 1;
        if (month == 12){
          year += 1;
          month = 1;
        } else {
          month += 1;
        }
      }
    }
  }
  
  
  String date = String(day) + "/" + String(month) + "/" + String(year);
  String time = String(hour) + ":" + String(min) + ":" + String(second);
  Serial.println(time);
  Serial.println(date);
  return date + "," + time;
}

// Phục vụ việc nhận dữ liệu điều khiển tới - tạm thời chưa dùng trong ứng dụng
void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for (int i = 0; i < length; i++) {
    Serial.print((char)payload[i]);
  }
  Serial.println();
}

// Connect lại tới server mqtt khi mất kết nối
void reconnect() {
  // Loop until we’re reconnected
  while (!client->connected()) {
    Serial.print("Attempting MQTT connection…");
    String clientId = "ESP8266";
    if (client->connect(clientId.c_str(), "esp8266", "Esp826612345")) {
      Serial.println("connected");
      // Once connected, publish an announcement…
      client->publish("testTopic", "hello world");
      // … and resubscribe
      client->subscribe("builtinLEDTopic");
    } else {
      Serial.print("failed, rc = ");
      Serial.print(client->state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
}

// Đợi để đọc đủ dữ liệu từ gps
static void smartDelay(unsigned long ms){
  unsigned long start = millis();
  while (millis() - start < ms){
    if(ss.available()){
      gps.encode(ss.read());
    }
  }
}

// Setup mạch
void setup() {
  delay(500);
  // When opening the Serial Monitor, select 9600 Baud
  Serial.begin(9600);
  ss.begin(GPSBaud);
  delay(500);

  Serial.print(F("Testing TinyGPSPlus library v. ")); Serial.println(TinyGPSPlus::libraryVersion());
  Serial.println(F("by Mikal Hart"));
  Serial.println();

  LittleFS.begin();
  setup_wifi();
  setDateTime();

  pinMode(LED_BUILTIN, OUTPUT); // Initialize the LED_BUILTIN pin as an output
  pinMode(waterLevel_Sensor, INPUT);
  pinMode(openDoor_Sensor, INPUT);
  // you can use the insecure mode, when you want to avoid the certificates
  //espclient->setInsecure();

  int numCerts = certStore.initCertStore(LittleFS, PSTR("/certs.idx"), PSTR("/certs.ar"));
  Serial.printf("Number of CA certs read: %d\n", numCerts);
  if (numCerts == 0) {
    Serial.printf("No certs found.\n");
    Serial.printf("Did you run certs-from-mozilla.py and upload the LittleFS directory before running?\n");
    return; // Can't connect to anything w/o certs!
  }

  BearSSL::WiFiClientSecure *bear = new BearSSL::WiFiClientSecure();
  // Integrate the cert store with this connection
  bear->setCertStore(&certStore);

  client = new PubSubClient(*bear);

  client->setServer(mqtt_server, 8883);
  client->setCallback(callback);
}

// Lặp tới khi hết pin....
void loop() {
  if (!client->connected()) {
    reconnect();
  }
  client->loop();

  unsigned long now = millis();
  if (now - lastMsg > 2000) {
    lastMsg = now;
    int waterLevel = analogRead(waterLevel_Sensor);
    int openDoor = digitalRead(openDoor_Sensor);

    bool check = false;
    // Delay for gps sensor
    if (ss.available()){
      smartDelay(1000);
      check = true;
    } else {
      Serial.println("ss not available");
    }

    if (millis() > 5000 && gps.charsProcessed() < 10)
      Serial.println(F("No GPS data received: check wiring"));

    String datetime = "-1";
    String latitude = "-1";
    String longtitude = "-1";
    bool isSetDateTime = false;

    String dt = getDateTimeNTP();
    if(!dt.equals("-1")){
      datetime = dt;
      isSetDateTime = true;
    }

    if(!isSetDateTime){
      if(gps.date.isValid() && gps.time.isValid()){
        datetime = parseToGMT7(gps.date.year(), gps.date.month(), gps.date.day(), gps.time.hour(), gps.time.minute(), gps.time.second());
      }
    }

    if(gps.location.isValid() && check){
      latitude = String(gps.location.lat());
      longtitude = String(gps.location.lng() + 2);
    }

    String sentMesseage = datetime + "," + latitude + "," + longtitude + "," 
                          + String(waterLevel) + "," + String(openDoor);

    Serial.print("Publish message: ");
    Serial.println(sentMesseage);
    
    client->publish("Tracking data", sentMesseage.c_str());
  }
}